### ISSUE TITLE
The type 'IDbConnection' is defined in an assembly that is not referenced.

### ISSUE THREAD

**Issue by svedaker** [naasking/Dapper.Compose#3]
Hi again!

I get this error when I try to use query.Execute. I assume that you should have dependency on System.Data.Common.

Error	CS0012	The type 'IDbConnection' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Data.Common, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by naasking** [comment]
Is Dapper added to your project? That should pull in all of the required dependencies.

Also, are you running on the .NET framework or .NET core? If the framework, what version? I just tried updating a project to the newest nuget release and it updates, builds and runs fine on a .NET core project.

**Comment by svedaker** [comment]
I'm using .net framework 4.6.1. If I add a reference to System.Data.Common it all works fine. I have "Dapper" version 1.50.2 with framework 4.5.2. Could be a problem with mixing frameworks. (Have both 4.5.2 on some common projects and 4.6.1 on some other)

**Comment by naasking** [comment]
That might be it. I target .NET standard 1.3 which requires .NET framework 4.6 or higher. Dapper has multiple build scripts to handle targeting multiple configurations and not just .NET standard, which I just don't have time to do, as described in issue #1.

Mixing framework versions probably works out for Dapper alone because it's built directly against the framework instead of the standard. If you can, try updating the 4.5.2 project up to 4.6 and see if that resolves the issue.

**Comment by naasking** [comment]
The lateset release targets multiple frameworks natively, so hopefully this is resolved.
